target ‘DubbingShow’ do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'PSTAlertController', '~> 1.2.0'
pod 'MLInputDodger', '~> 1.3.0'
pod 'SMPageControl', '~> 1.2'
pod 'iCarousel', '~> 1.8.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'JSONModel', '~> 1.1.2'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'MJRefresh', '~> 3.0.6'
pod 'Masonry', '~> 0.6.3'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'SDCycleScrollView','~> 1.3'
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'YYWebImage', '~> 0.9.11'
pod 'TTTAttributedLabel', '1.10.1'
pod 'hpple', '0.2.0'
pod 'ReactiveCocoa', '2.3.1'
pod 'XHSinaMenuView', '~> 1.4'
pod 'POP+MCAnimate', '2.0.1'
pod 'MJExtension'

end
